### PR TITLE
Fix three issues in boilerplate

### LINKED ISSUE #4: Cannot find module '@pulumi/pulumi'
Hi!

I've followed the steps in the readme to run the example, but when i run `pulumi up` I get the following exception:

```
 pulumi:pulumi:Stack (simple-test):
    error: Running program 'C:\repos\pulumi-provider-boilerplate\examples\simple' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    ../../sdk/nodejs/provider.ts(4,25): error TS2307: Cannot find module '@pulumi/pulumi'.

        at createTSError (C:\repos\pulumi-provider-boilerplate\examples\simple\node_modules\ts-node\src\index.ts:261:12)
        at getOutput (C:\repos\pulumi-provider-boilerplate\examples\simple\node_modules\ts-node\src\index.ts:367:40)
        at Object.compile (C:\repos\pulumi-provider-boilerplate\examples\simple\node_modules\ts-node\src\index.ts:558:11)
        at Module.m._compile (C:\repos\pulumi-provider-boilerplate\examples\simple\node_modules\ts-node\src\index.ts:439:43)
        at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
        at Object.require.extensions.<computed> [as .ts] (C:\repos\pulumi-provider-boilerplate\examples\simple\node_modules\ts-node\src\index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:628:32)
        at Function.Module._load (internal/modules/cjs/loader.js:555:12)
        at Module.require (internal/modules/cjs/loader.js:666:19)
        at require (internal/modules/cjs/helpers.js:16:16)
```

Any idea?

### PR DESCRIPTION
**Pull request by lukehoban**
The Makefile was deleting the .NET SDK immediately after generating it.  Fix this to delete it before re-generating it instead.

The schema did not include dependencies on Pulumi, which led to at least the .NET SDK not compiling out of the box.

Also re-generates all SDKs with the latest changes to the code generators from recent PRs so that this is self-consistently up to date.

Fixes #4.

### CODE REVIEW

File: sdk/dotnet/Provider.cs [hunk 1]
```diff
@@ -1,4 +1,4 @@
-// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
+// *** WARNING: this file was generated by pulumigen. ***
```
Comment (lukehoban) [inline sdk/dotnet/Provider.cs:1]: I don't love this.  We may want to undo the part of the change in https://github.com/pulumi/pulumi-provider-boilerplate/pull/11/files#diff-edba8f02af121e983e5788bc4949c74194a91b7a212cfec8617c4a1799c8ae77L53 that changed this.  We may also want to align with back up into the native providers where I assume this came from?

**Review by mikhailshilkov — APPROVED** [review]
Thank you!
